// SPDX-FileCopyrightText: Advanced Micro Devices, Inc.
// SPDX-License-Identifier: Apache-2.0

//! `pichi update [<dir>]` — resolve the carapace references in
//! `<dir>/pichi.build/*.yaml` and write `<dir>/pichi.build/refs.lock`
//! (BUILD.md §2.4, §14).
//!
//! MVP scope: references are taken from `carapace.yaml` (`from:`) and
//! `pmi.yaml` (`from:`); `config.yaml` `carapaces:` are deferred with the
//! rest of the config-filter work. Each reference must already be in the
//! local cache (no registry pull yet). For each, the lock records the
//! manifest digest (sha256 over the OCI manifest bytes) and the
//! carapace's top-scute dm-verity root (`rootₙ₋₁`).

#![cfg_attr(test, allow(clippy::unwrap_used))]

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow, bail};

use conglobate::{CarapaceRecipe, LockEntry, PmiRecipe, RefsLock};
use pichi_artifact::{Digest, Manifest, Reference, ReferenceKind};
use pichi_storage::{BlobStore, FilesystemBlobStore, FilesystemTagDb, TagDb};

use crate::cli::UpdateArgs;
use crate::cmd::manifest_ext::ManifestExt;
use crate::config::Config;

/// Generated-file header prepended to `refs.lock` (BUILD.md §2.4).
const LOCK_HEADER: &str = "# pichi.build/refs.lock — generated by `pichi update`; do not edit\n";

pub async fn run(args: UpdateArgs, config: &Config) -> Result<()> {
    let dir = args.dir.unwrap_or_else(|| PathBuf::from("."));
    let build_dir = dir.join("pichi.build");
    if !build_dir.is_dir() {
        bail!(
            "no pichi.build/ directory under {} (run from a pichi project)",
            dir.display()
        );
    }

    let refs = collect_refs(&build_dir)?;

    // Build the whole lock before touching disk — "makes no changes until
    // all content validates" (BUILD.md §14).
    let lock = if refs.is_empty() {
        RefsLock::default()
    } else {
        let layout = config.resolve_layout()?;
        let db = FilesystemTagDb::open(&layout.graphroot)?;
        let blob_store = FilesystemBlobStore::new(&layout.graphroot);

        let mut entries: BTreeMap<String, LockEntry> = BTreeMap::new();
        for reference in refs {
            let (manifest_digest, manifest) =
                resolve_manifest(&reference, &db, &blob_store).await?;
            let top_root = manifest
                .carapace_top_root(&blob_store)
                .await
                .with_context(|| format!("computing carapace root for {reference}"))?;
            entries.insert(
                reference,
                LockEntry {
                    manifest: manifest_digest.to_string(),
                    carapace: format!("sha256:{}", hex::encode(top_root)),
                },
            );
        }
        RefsLock { entries }
    };

    let lock_path = build_dir.join("refs.lock");
    let body = lock.to_yaml().context("serializing refs.lock")?;
    std::fs::write(&lock_path, format!("{LOCK_HEADER}{body}"))
        .with_context(|| format!("writing {}", lock_path.display()))?;

    println!(
        "pichi update: pinned {} reference(s) -> {}",
        lock.entries.len(),
        lock_path.display()
    );
    Ok(())
}

/// Read `carapace.yaml` (`from:`) and `pmi.yaml` (`from:`, if present) and
/// return the unique carapace references, sorted.
fn collect_refs(build_dir: &Path) -> Result<Vec<String>> {
    let mut refs: BTreeSet<String> = BTreeSet::new();

    let carapace_yaml = build_dir.join("carapace.yaml");
    if carapace_yaml.is_file() {
        let text = std::fs::read_to_string(&carapace_yaml)
            .with_context(|| format!("reading {}", carapace_yaml.display()))?;
        let recipe = CarapaceRecipe::parse(&text)
            .with_context(|| format!("parsing {}", carapace_yaml.display()))?;
        refs.insert(recipe.from);
    }

    let pmi_yaml = build_dir.join("pmi.yaml");
    if pmi_yaml.is_file() {
        let text = std::fs::read_to_string(&pmi_yaml)
            .with_context(|| format!("reading {}", pmi_yaml.display()))?;
        let recipe =
            PmiRecipe::parse(&text).with_context(|| format!("parsing {}", pmi_yaml.display()))?;
        if let Some(from) = recipe.from {
            refs.insert(from);
        }
    }

    Ok(refs.into_iter().collect())
}

/// Resolve a cached reference to its manifest digest + parsed manifest.
async fn resolve_manifest(
    reference: &str,
    db: &FilesystemTagDb,
    blob_store: &FilesystemBlobStore,
) -> Result<(Digest, Manifest)> {
    let target: Reference = reference
        .parse()
        .with_context(|| format!("invalid reference: {reference}"))?;
    let digest = match &target.kind {
        ReferenceKind::Digest(d) => d.clone(),
        ReferenceKind::Tag(_) => {
            let key = target.to_string();
            db.resolve_tag(&key).await?.ok_or_else(|| {
                anyhow!(
                    "ref not in cache: {key}\n  hint: pichi pull {key} (then re-run pichi update)"
                )
            })?
        }
    };
    let bytes = blob_store
        .get_blob(&digest)
        .await
        .with_context(|| format!("reading manifest blob {digest}"))?;
    let manifest = Manifest::from_reader_validated(bytes.as_slice())
        .with_context(|| format!("validating manifest {digest}"))?;
    Ok((digest, manifest))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Config, StorageConfig};
    use pichi_import::{cow, verity};
    use tempfile::TempDir;

    /// `pichi update` pins an imported carapace's reference with the exact
    /// top-scute root the importer produced — verified against an
    /// independent `cow::write` + `verity::compute` over the same image.
    #[tokio::test]
    async fn pins_imported_carapace_root() {
        let tmp = TempDir::new().unwrap();
        let graphroot = tmp.path().join("storage");
        std::fs::create_dir_all(&graphroot).unwrap();

        // A small raw image with one non-zero chunk.
        let mut raw = vec![0u8; 64 * 1024];
        raw[20_000] = 0x42;
        let raw_path = tmp.path().join("img.raw");
        std::fs::write(&raw_path, &raw).unwrap();

        // Independent expected single-scute root, the way the importer
        // computes it: the carapace-mandated scute chunk size, verity over
        // 4096-byte blocks with the 32-byte zero salt (uuid irrelevant).
        let cow_bytes = cow::write(&raw, pichi_import::SCUTE_CHUNK_SIZE_SECTORS).unwrap();
        let params = verity::VerityParams {
            data_block_size: 4096,
            hash_block_size: 4096,
            salt: vec![0u8; 32],
            uuid: [0u8; 16],
        };
        let expected_root = params.compute(&cow_bytes).unwrap().root_hash;

        // Import it into the cache as `base:1`.
        pichi_import::run(
            pichi_import::ImportArgs {
                raw_image: raw_path,
                tag: "base:1".into(),
                salt_suffix: None,
                quiet: true,
                print_verity_info: false,
                created_rfc3339: "2026-06-22T00:00:00Z".into(),
                pmi: None,
                dtb: None,
                config_json: None,
            },
            &graphroot,
        )
        .await
        .unwrap();

        // A project that derives from it.
        let project = tmp.path().join("proj");
        std::fs::create_dir_all(project.join("pichi.build")).unwrap();
        std::fs::write(
            project.join("pichi.build").join("carapace.yaml"),
            "from: base:1\n",
        )
        .unwrap();

        let config = Config {
            storage: StorageConfig {
                graphroot: Some(graphroot),
                ..Default::default()
            },
            ..Default::default()
        };
        run(
            UpdateArgs {
                dir: Some(project.clone()),
            },
            &config,
        )
        .await
        .unwrap();

        let lock_text =
            std::fs::read_to_string(project.join("pichi.build").join("refs.lock")).unwrap();
        let lock = conglobate::RefsLock::parse(&lock_text).unwrap();
        let entry = lock.get("base:1").expect("base:1 must be pinned");
        assert_eq!(
            entry.carapace,
            format!("sha256:{}", hex::encode(expected_root))
        );
        assert!(entry.manifest.starts_with("sha256:"), "{}", entry.manifest);
    }
}
