#!/usr/bin/env bash
# Generate too_many_cpus.dts: 257 vCPUs — one past CPU_CACHE_CAP and
# one past MADT's u8 processor_id limit. count's walk_cpus rejects
# the 257th cpu as DtbError::TooManyCpus { limit: 256 }.

set -euo pipefail
cd "$(dirname "$0")"

N_CPUS=257

{
    cat <<'HEADER'
/dts-v1/;

/* GENERATED by generate_too_many_cpus.sh — do not edit by hand. */

/ {
	#address-cells = <2>;
	#size-cells = <2>;
	model = "dtb2acpi-test/too_many_cpus";
	compatible = "dtb2acpi,test-too-many-cpus";

	cpus {
		#address-cells = <1>;
		#size-cells = <0>;

HEADER

    for i in $(seq 0 $((N_CPUS - 1))); do
        printf '\t\tcpu@%x {\n' "$i"
        printf '\t\t\tdevice_type = "cpu";\n'
        printf '\t\t\treg = <0x%x>;\n' "$i"
        printf '\t\t\tcompatible = "intel,x86";\n'
        printf '\t\t};\n\n'
    done

    cat <<'FOOTER'
	};

	lapic: interrupt-controller@fee00000 {
		compatible = "intel,ce4100-lapic";
		reg = <0x0 0xfee00000 0x0 0x1000>;
		interrupt-controller;
		#interrupt-cells = <2>;
	};

	ioapic: interrupt-controller@fec00000 {
		compatible = "intel,ce4100-ioapic";
		reg = <0x0 0xfec00000 0x0 0x1000>;
		interrupt-controller;
		#interrupt-cells = <2>;
	};

	poweroff@9010000 {
		compatible = "syscon-poweroff";
		reg = <0x0 0x9010000 0x0 0x4>;
		value = <0x34>;
	};
};
FOOTER
} > too_many_cpus.dts

dtc -q -I dts -O dtb -o too_many_cpus.dtb too_many_cpus.dts
echo "generated too_many_cpus.dts ($(wc -c < too_many_cpus.dts) bytes) and too_many_cpus.dtb ($(wc -c < too_many_cpus.dtb) bytes)"
