#!/usr/bin/env bash
# Generate many_cpus.dts: 256 vCPUs with sequential APIC IDs 0..255.
# Exercises the MADT Type 10 (x2APIC NMI) path, which triggers when
# processor UID > 254. The existing cpu_high_apic_id fixture covers
# Type 9 (Processor Local x2APIC, triggered by APIC ID > 254) with
# only 2 vCPUs, but Type 10 specifically needs UID > 254.
#
# Modern clouds routinely ship VMs with this many vCPUs (Azure HBv4
# 176, AWS r7i 192, GCP c3 176, bare-metal often 384+).

set -euo pipefail
cd "$(dirname "$0")"

N_CPUS=256

{
    cat <<'HEADER'
/dts-v1/;

/* GENERATED by generate_many_cpus.sh — do not edit by hand. */

/ {
	#address-cells = <2>;
	#size-cells = <2>;
	model = "dtb2acpi-test/many_cpus";
	compatible = "dtb2acpi,test-many-cpus";

	cpus {
		#address-cells = <1>;
		#size-cells = <0>;

HEADER

    for i in $(seq 0 $((N_CPUS - 1))); do
        printf '\t\tcpu@%x {\n' "$i"
        printf '\t\t\tdevice_type = "cpu";\n'
        printf '\t\t\treg = <0x%x>;\n' "$i"
        printf '\t\t\tcompatible = "intel,x86";\n'
        printf '\t\t};\n\n'
    done

    cat <<'FOOTER'
	};

	lapic: interrupt-controller@fee00000 {
		compatible = "intel,ce4100-lapic";
		reg = <0x0 0xfee00000 0x0 0x1000>;
		interrupt-controller;
		#interrupt-cells = <2>;
	};

	ioapic: interrupt-controller@fec00000 {
		compatible = "intel,ce4100-ioapic";
		reg = <0x0 0xfec00000 0x0 0x1000>;
		interrupt-controller;
		#interrupt-cells = <2>;
	};

	poweroff@9010000 {
		compatible = "syscon-poweroff";
		reg = <0x0 0x9010000 0x0 0x4>;
		value = <0x34>;
	};
};
FOOTER
} > many_cpus.dts

dtc -q -I dts -O dtb -o many_cpus.dtb many_cpus.dts
echo "generated many_cpus.dts ($(wc -c < many_cpus.dts) bytes) and many_cpus.dtb ($(wc -c < many_cpus.dtb) bytes)"
